class BookCreation < ActiveRecord::Migration[7.1]
  def change
    Book.create!(title: "Naturalis historia", author: "Pliny the Elder", publish_year: 1469)
    Book.create!(title: "The Wind in the Willows", author: "Kenneth Grahame", publish_year: 1908)
    Book.create!(title: "The Turn of the Screw", author: "Henry James", publish_year: 1898)
    Book.create!(title: "History of the Decline and Fall of the Roman Empire Complete and Unabridged", author: "Edward Gibbon", publish_year: 1776)
    Book.create!(title: "Taming of the Shrew", author: "William Shakespeare", publish_year: 1631)
    Book.create!(title: "The Lord of the Rings", author: "J.R.R. Tolkien", publish_year: 1954)
    Book.create!(title: "The Return of the Native", author: "Thomas Hardy", publish_year: 1878)
    Book.create!(title: "The Story of Philosophy", author: "Will Durant", publish_year: 1926)
    Book.create!(title: "The Lion, the Witch and the Wardrobe", author: "C.S. Lewis", publish_year: 1950)
    Book.create!(title: "The alchemist, 1612", author: "Ben Jonson", publish_year: 1612)
    Book.create!(title: "The Prince and the Pauper", author: "Mark Twain", publish_year: 1881)
    Book.create!(title: "The Call of the Wild", author: "Jack London", publish_year: 1903)
    Book.create!(title: "Voyage au Centre de la Terre", author: "Jules Verne", publish_year: 1867)
    Book.create!(title: "The Enduring Vision", author: "Paul S. Boyer", publish_year: 1987)
    Book.create!(title: "On The Road", author: "Jack Kerouac", publish_year: 1957)
    Book.create!(title: "The War of the Worlds", author: "H. G. Wells", publish_year: 1898)
    Book.create!(title: "On the Beach.", author: "Nevil Shute", publish_year: 1957)
    Book.create!(title: "The Murder at the Vicarage", author: "Agatha Christie", publish_year: 1930)
    Book.create!(title: "The Last of the Mohicans", author: "James Fenimore Cooper", publish_year: 1826)
    Book.create!(title: "The First Men in the Moon", author: "H. G. Wells", publish_year: 1900)
    Book.create!(title: "The life of Olaudah Equiano, or Gustavus Vassa, the African", author: "Olaudah Equiano", publish_year: 1789)
    Book.create!(title: "The Curious Incident of the Dog in the Night-Time", author: "Mark Haddon", publish_year: 1950)
    Book.create!(title: "The Hitch Hiker's Guide to the Galaxy", author: "Douglas Adams", publish_year: 1979)
    Book.create!(title: "The Martian Chronicles", author: "Ray Bradbury", publish_year: 1950)
    Book.create!(title: "The Return of the King", author: "J.R.R. Tolkien", publish_year: 1950)
    Book.create!(title: "The food of the gods and how it came to earth", author: "H. G. Wells", publish_year: 1900)
    Book.create!(title: "Записки изъ подполья", author: "Фёдор Михайлович Достоевский", publish_year: 1864)
    Book.create!(title: "The Fellowship of the Ring", author: "J.R.R. Tolkien", publish_year: 1954)
    Book.create!(title: "The Catcher in the Rye", author: "J. D. Salinger", publish_year: 1900)
    Book.create!(title: "To the Lighthouse", author: "Virginia Woolf", publish_year: 1927)
    Book.create!(title: "The Murders in the Rue Morgue", author: "Edgar Allan Poe", publish_year: 1895)
    Book.create!(title: "The Wealth of Nations", author: "Adam Smith", publish_year: 1776)
    Book.create!(title: "The Second World War", author: "Winston S. Churchill", publish_year: 1948)
    Book.create!(title: "The Old Man and the Sea", author: "Ernest Hemingway", publish_year: 1952)
    Book.create!(title: "Tender is the Night", author: "F. Scott Fitzgerald", publish_year: 1933)
    Book.create!(title: "The Body in the Library", author: "Agatha Christie", publish_year: 1942)
    Book.create!(title: "The Hound of the Baskervilles", author: "Arthur Conan Doyle", publish_year: 1900)
    Book.create!(title: "Life on the Mississippi", author: "Mark Twain", publish_year: 1883)
    Book.create!(title: "Far From the Madding Crowd", author: "Thomas Hardy", publish_year: 1874)
    Book.create!(title: "The Silver Chair", author: "C.S. Lewis", publish_year: 1953)
    Book.create!(title: "Chemistry", author: "Theodore L. Brown", publish_year: 1977)
    Book.create!(title: "The Two Towers", author: "J.R.R. Tolkien", publish_year: 1954)
    Book.create!(title: "The Twits", author: "Roald Dahl", publish_year: 1967)
    Book.create!(title: "The Canterbury Tales", author: "Geoffrey Chaucer", publish_year: 1478)
    Book.create!(title: "The Ugly Duckling", author: "Hans Christian Andersen", publish_year: 1851)
    Book.create!(title: "The Jungle", author: "Upton Sinclair", publish_year: 1905)
    Book.create!(title: "The Pearl", author: "John Steinbeck", publish_year: 1945)
    Book.create!(title: "The Sign of Four", author: "Arthur Conan Doyle", publish_year: 1889)
    Book.create!(title: "The Mystery of the Blue Train", author: "Agatha Christie", publish_year: 1928)
    Book.create!(title: "Murder on the Links", author: "Agatha Christie", publish_year: 1923)
    Book.create!(title: "Tempest", author: "William Shakespeare", publish_year: 1611)
    Book.create!(title: "Der Zauberberg", author: "Thomas Mann", publish_year: 1924)
    Book.create!(title: "The Godfather", author: "Mario Puzo", publish_year: 1969)
    Book.create!(title: "The Moonstone", author: "Wilkie Collins", publish_year: 1868)
    Book.create!(title: "The Silmarillion", author: "J.R.R. Tolkien", publish_year: 1977)
    Book.create!(title: "The Giver", author: "Lois Lowry", publish_year: 1993)
    Book.create!(title: "Le fantôme de l'opéra", author: "Gaston Leroux", publish_year: 1911)
    Book.create!(title: "The Complete Sherlock Holmes [4 novels, 56 stories]", author: "Arthur Conan Doyle", publish_year: 1900)
    Book.create!(title: "When the Sleeper Awakes", author: "H.G. Wells", publish_year: 1899)
    Book.create!(title: "Lord of Flies", author: "William Golding", publish_year: 1954)
    Book.create!(title: "The Big Sleep", author: "Raymond Chandler", publish_year: 1939)
    Book.create!(title: "The Witches", author: "Roald Dahl", publish_year: 1983)
    Book.create!(title: "The Beautiful and Damned", author: "F. Scott Fitzgerald", publish_year: 1922)
    Book.create!(title: "The Marvelous Land of Oz", author: "L. Frank Baum", publish_year: 1904)
    Book.create!(title: "The Scarlet Letter", author: "Nathaniel Hawthorne", publish_year: 1850)
    Book.create!(title: "Death in the Clouds", author: "Agatha Christie", publish_year: 1935)
    Book.create!(title: "The Man in the Brown Suit", author: "Agatha Christie", publish_year: 1924)
    Book.create!(title: "Works [37 plays, 6 poems, sonnets]", author: "William Shakespeare", publish_year: 1730)
    Book.create!(title: "Εὐθύφρων / Κρίτων / Φαίδων / Ἀπολογία Σωκράτους", author: "Πλάτων", publish_year: 1871)
    Book.create!(title: "The Magician's Nephew", author: "C.S. Lewis", publish_year: 1955)
    Book.create!(title: "The Last Battle", author: "C.S. Lewis", publish_year: 1956)
    Book.create!(title: "The Castle of Otranto", author: "Horace Walpole", publish_year: 1764)
    Book.create!(title: "The Invisible Man", author: "H. G. Wells", publish_year: 1897)
    Book.create!(title: "Tess of the d'Urbervilles", author: "Thomas Hardy", publish_year: 1707)
    Book.create!(title: "Le Morte d'Arthur", author: "Thomas Malory", publish_year: 1557)
    Book.create!(title: "The Art of War", author: "Sun Tzu", publish_year: 1910)
    Book.create!(title: "Winnie-the-Pooh", author: "A. A. Milne", publish_year: 1925)
    Book.create!(title: "The Age of Innocence", author: "Edith Wharton", publish_year: 1920)
    Book.create!(title: "La chute", author: "Albert Camus", publish_year: 1917)
    Book.create!(title: "The Time Machine", author: "H. G. Wells", publish_year: 1895)
    Book.create!(title: "Anne of the Island", author: "Lucy Maud Montgomery", publish_year: 1915)
    Book.create!(title: "The House of Mirth", author: "Edith Wharton", publish_year: 1905)
    Book.create!(title: "The Portrait Of A Lady", author: "Luther T. Smith", publish_year: 1881)
    Book.create!(title: "The Night Before Christmas", author: "Clement Clarke Moore", publish_year: 1857)
    Book.create!(title: "On the origin of species by means of natural selection", author: "Charles Darwin", publish_year: 1859)
    Book.create!(title: "For Whom the Bell Tolls", author: "Ernest Hemingway", publish_year: 1940)
    Book.create!(title: "The Secret Garden", author: "Frances Hodgson Burnett", publish_year: 1911)
    Book.create!(title: "The Iron Heel", author: "Jack London", publish_year: 1907)
    Book.create!(title: "Inferno", author: "Dante Alighieri", publish_year: 1782)
    Book.create!(title: "The Good Earth", author: "Pearl S. Buck", publish_year: 1548)
    Book.create!(title: "The Merchant of Venice", author: "William Shakespeare", publish_year: 1600)
    Book.create!(title: "The Travels of Marco Polo", author: "Marco Polo", publish_year: 1818)
    Book.create!(title: "Ὀδύσσεια", author: "Όμηρος", publish_year: 1488)
    Book.create!(title: "The Awakening", author: "Kate Chopin", publish_year: 1899)
    Book.create!(title: "The Voyage of the Dawn Treader", author: "C.S. Lewis", publish_year: 1952)
    Book.create!(title: "The Hobbit", author: "J.R.R. Tolkien", publish_year: 1937)
    Book.create!(title: "Narrative of the life of Frederick Douglass, an American slave", author: "Frederick Douglass", publish_year: 1845)
    Book.create!(title: "Through the Looking-Glass", author: "Lewis Carroll", publish_year: 1871)
    Book.create!(title: "The Prophet", author: "Kahlil Gibran", publish_year: 1900)
    Book.create!(title: "Othello", author: "William Shakespeare", publish_year: 1622)
    Book.create!(title: "Harry Potter and the Philosopher's Stone", author: "J. K. Rowling", publish_year: 1997)
    Book.create!(title: "Harry Potter and the Order of the Phoenix", author: "J. K. Rowling", publish_year: 2003)
    Book.create!(title: "Harry Potter and the Deathly Hallows", author: "J. K. Rowling", publish_year: 2007)
    Book.create!(title: "Harry Potter and the Prisoner of Azkaban", author: "J. K. Rowling", publish_year: 1999)
    Book.create!(title: "Harry Potter and the Chamber of Secrets", author: "J. K. Rowling", publish_year: 1998)
    Book.create!(title: "Harry Potter and the Half-Blood Prince", author: "J. K. Rowling", publish_year: 2005)
    Book.create!(title: "Harry Potter and the Goblet of Fire", author: "J. K. Rowling", publish_year: 1993)
  end
end
